### ISSUE TITLE
 一个BUG，和几点建议

### ISSUE THREAD

**Issue by zhangzixun** [Wygdbb/OpenWRT-For-Pi#1]
首先，向您表示感谢！
我在网上找了两天，测试了几个固件，终于找到一个好用的固件，也就是您编译的固件。
然而，我对比了一下其他固件，建议这个固件略作改进。

一个BUG
我发现，固件的主题更改后，重启以后会再次变为NETGEAR主题。

几点建议
1）平时在外面，有访问家里NAS的需求，最简单的办法，就是通过L2TP连接家里的网络。
因此，建议增加L2TP服务器的功能。据我所知，Padavan 用SoftEther 实现了这个功能，效果不错。
2）通常情况下，Orange Pi Zero 作为旁路有接入系统。默认情况下，网卡接口应该是WAN口，且应该允许通过DHCP方式获取IP。当然，不排除电脑用LAN连接 Orange Pi。如果可能，建议安装内置无线网卡驱动。有线接口为WAN口，无线接口为LAN口。电脑通过无线网卡连接OrangePi，并配置。

**Comment by Wygdbb** [comment]
> 1

谢谢你给我反馈，我会在新固件中做出修改。固件属于个人定制版，如有顾及不到的地方，请多担待。

**Comment by Wygdbb** [comment]
> 首先，向您表示感谢！
> 我在网上找了两天，测试了几个固件，终于找到一个好用的固件，也就是您编译的固件。
> 然而，我对比了一下其他固件，建议这个固件略作改进。
> 
> 一个BUG
> 我发现，固件的主题更改后，重启以后会再次变为NETGEAR主题。
> 
> 几点建议
> 1）平时在外面，有访问家里NAS的需求，最简单的办法，就是通过L2TP连接家里的网络。
> 因此，建议增加L2TP服务器的功能。据我所知，Padavan 用SoftEther 实现了这个功能，效果不错。
> 2）通常情况下，Orange Pi Zero 作为旁路有接入系统。默认情况下，网卡接口应该是WAN口，且应该允许通过DHCP方式获取IP。当然，不排除电脑用LAN连接 Orange Pi。如果可能，建议安装内置无线网卡驱动。有线接口为WAN口，无线接口为LAN口。电脑通过无线网卡连接OrangePi，并配置。

谢谢你给我的反馈  我会在新固件中做出改正。
