### ISSUE TITLE
能增加CPU的频率、温度显示么？

### ISSUE THREAD

**Issue by dhobii** [Wygdbb/OpenWRT-For-Pi#5]
撤回我的问题。
OpenWrt，没有NEO、NEO2的i2c驱动，官源版本无法驱动oled，无CPU温度频率传感器。
交叉编译，FriendlyWrt与OpenWrt杂交。
使用FriendlyWrt的uboot、kernel，使用OpenWrt的rootfs。

**Comment by Wygdbb** [comment]
CPU温度和频率不是刚需，对使用来说没啥影响。所以就没折腾过，找了一篇文章，你试试吧https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=1358471
https://www.popyone.com/post/30.html

**Comment by dhobii** [comment]
我要放弃了，折腾了很长时间了。
NanoPi NEO2的问题是，在FriendlyCore下正常，CPU频率和温度的传感器是有的。
但是，在openwrt，连CPU频率和温度的传感器都没有。
我使用sunxi官网的arm64-dts-allwinner-h5-Enable-CPU-DVFS-cpufreq.patch补丁，编译报错；只使用neo2的部分，固件无法启动。
从FriendlyCore中提取sun50i-h5-nanopi-neo2.dtb，反编译为dts文件，拷贝到openwrt中编译，固件无法启动。

在openwrt下，传感器硬件都不存在。。。。。
root@OpenWrt:/# cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq
cat: can't open '/sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq': No such file or directory

root@OpenWrt:/# cat /sys/class/thermal/thermal_zone0/temp
cat: can't open '/sys/class/thermal/thermal_zone0/temp': No such file or directory
