### ISSUE TITLE
求添加这个主题。我也不知道这个主题源码地址，麻烦您找找加下，非常感谢。

### ISSUE THREAD

**Issue by OPnb** [Wygdbb/OpenWRT-For-Pi#6]
![图片](https://user-images.githubusercontent.com/67452171/94397492-89968f80-0196-11eb-9909-1b89b398d047.png)

**Comment by dhobii** [comment]
https://github.com/jerrykuku/luci-theme-argon

**Comment by Wygdbb** [comment]
好的，收到

**Comment by Wygdbb** [comment]
> https://github.com/jerrykuku/luci-theme-argon

收到，会在之后的版本中添加

**Comment by Wygdbb** [comment]
该主题已经被添加，请下载最新的固件即可。
